
source "https://rubygems.org"
ruby '2.0.0'

gem 'capistrano', '~> 3.4.0'
gem 'capistrano-bundler', '~> 1.1.2'
gem 'faraday'
gem 'haml'
gem 'hashie'
gem 'json'
gem 'puma'
gem 'pry'
gem 'pry-byebug'
gem 'pry-rescue'
gem 'rack-contrib'
gem 'redis'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'typhoeus'
